Support jq as an operation.
gchq/CyberChef pull request #1604
Opened 2023-07-25 06:44 UTC by zhzy0077

fixes #1110

2023-07-25 06:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gchq/CyberChef?pullRequest=1604) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gchq/CyberChef?pullRequest=1604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gchq/CyberChef?pullRequest=1604) it.</sub>

2024-07-10 12:29 UTC, xi-ao commented
It's been a year. Is there any plan to merge this PR anytime soon?

2025-02-16 02:04 UTC, a3957273 commented
Hey! This pull request has gotten rather old and that's our fault. This project stopped being actively maintained for a while and it looks like your pull request has started to gather dust. Would you be able to update your branch to the latest version of CyberChef and we'll give it a review?

2025-02-17 05:53 UTC, zhzy0077 commented
> Hey! This pull request has gotten rather old and that's our fault. This project stopped being actively maintained for a while and it looks like your pull request has started to gather dust. Would you be able to update your branch to the latest version of CyberChef and we'll give it a review?

Thanks for looking into this! I have updated the branch and solved comments.

2025-02-17 06:19 UTC, xi-ao commented
That would be awesome! :smiley:

2025-03-04 07:56 UTC, xi-ao commented
@a3957273 Don't forget it again :wink:

2025-03-09 23:07 UTC, a3957273 requested changes

2025-03-09 23:07 UTC, a3957273 commented on src/core/config/Categories.json
> +            "jq",
I suspect this should be `Jq` or `JQ` to keep with the theme of the rest of these operations, although I realise `jq` is more natural based on the CLI usage of it.

2025-03-09 23:07 UTC, a3957273 commented on src/core/operations/Jq.mjs
> +import jq from "jq-web";
This import seems to increase the size of the bundle by around 3-4MB, including the size of "Code" modules from 700KB transferred to 4MB transferred.  I suspect there's not a lighter-weight way of doing this, but would it be possible to put it in it's own module?  The "Code" module is used by a bunch of other operators.

2025-03-12 12:17 UTC, zhzy0077 commented on src/core/config/Categories.json
> +            "jq",
Renamed to "Jq"

2025-04-03 07:15 UTC, a3957273 commented
Awesome!  No base package increase now.  I'll get this merged in. :)

2025-04-03 07:15 UTC, merged