fix: Updated bcrypt library to resolve compatibility issue (#1853)
gchq/CyberChef pull request #1857
Opened 2024-07-06 13:32 UTC by shivansh84ya

fix: Updated bcrypt library to resolve compatibility issue (#1853)

- Updated the bcrypt library to the latest version to support hashes beginning with '$2b'.
- Implemented changes to ensure backward compatibility with existing hashes.
- Verified functionality using the provided test case with 'Bcrypt compare' in CyberChef.

Resolves: #1853

2024-07-06 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gchq/CyberChef?pullRequest=1857) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gchq/CyberChef?pullRequest=1857) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gchq/CyberChef?pullRequest=1857) it.</sub>

2024-07-06 16:43 UTC, jonycoo commented
According to the failing Test, the BcryptCompare.mjs  has not been changed to the new Library.
The other Error: failing to find index.mjs
does not seem to come directly from the changes, it may be a secondery side-effect from the first one.

2024-07-06 16:47 UTC, jonycoo requested changes
According to the failing Test, the BcryptCompare.mjs has not been changed to the new Library.
The other Error: failing to find index.mjs
does not seem to come directly from the changes, it may be a secondery side-effect from the first one.

2024-07-06 16:50 UTC, shivansh84ya commented
@jonycoo 
I will investigate this more and address these issues before resubmitting the pull request.

2025-02-16 02:05 UTC, a3957273 commented
Hey! This pull request has gotten rather old and that's our fault. This project stopped being actively maintained for a while and it looks like your pull request has started to gather dust. Would you be able to update your branch to the latest version of CyberChef and we'll give it a review?

2025-02-21 22:17 UTC, a3957273 commented on package.json
> +    "bcrypt": "^5.1.1",
`bcrypt`, which requires `node-gyp`, supports a far fewer subset of Node versions than `bcryptjs`.  Does the `bcryptjs` package also support the necessary functionality?

2026-06-27 22:34 UTC, GCHQDeveloper581 commented
No longer required as the original bcryptjs library has been updated and now handles $2b format hashes.

2026-06-27 22:34 UTC, closed without merging