Disjoin Operation
gchq/CyberChef pull request #457
Opened 2018-12-29 01:21 UTC by masq

Adds in the "Disjoin" operation, which attempts to satisfy the operation requested in [issue #424](https://github.com/gchq/CyberChef/issues/424).

I say attempts, as I'm not really sure how other types of flow operations should affect/be affected by this operation. For example, if one of the proceeding operations was a "jump" operation. I made a test out of the example provided in the issue, and that passes, but I was a little unsure of the full utility that the operation could provide, and would love to see more examples of this in order to fully flush it out.

I also heavily modeled the code based on the "Fork" operation's implementation, and there were a few things in there that I'm not sure are necessary for this operation that were present in the "Fork" operation. So, I would love a code review to look for things that were unnecessarily copied over. Just let me know! Thanks!

2024-02-17 13:06 UTC, mattnotmitt requested changes

2024-02-17 13:06 UTC, mattnotmitt commented on src/core/operations/Disjoin.mjs
> +                subRec.addOperations(opList[i]);
`addOperations` takes a list of operations, should probably be
`subRec.addOperations[opList[i]]`

2024-02-17 13:06 UTC, mattnotmitt commented on src/core/operations/Disjoin.mjs
> +            const ingValues = recipe.opList.map(op => JSON.parse(JSON.stringify(op.ingValues)));
Could use [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) instead

2024-02-17 13:06 UTC, mattnotmitt commented on src/core/operations/Disjoin.mjs
> +        this.name = "Disjoin";
Still not sure how I feel about the name `Disjoin`. Perhaps `Concurrently`?

2025-02-16 02:06 UTC, a3957273 commented
Hey! This pull request has gotten rather old and that's our fault. This project stopped being actively maintained for a while and it looks like your pull request has started to gather dust. Would you be able to update your branch to the latest version of CyberChef and we'll give it a review?

2025-04-03 07:25 UTC, closed without merging